version: '3.9'

services:
  db:
    image: postgres:latest
    hostname: '127.0.0.1'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ads_base

